---
- name: Москва
  lat:  55.75
  lon:  37.62
- name: Санкт-Петербург
  lat:  59.94
  lon:  30.31
- name: Красноярск
  lat:  56.02
  lon:  92.87
- name: Новосибирск
  lat:  55.04
  lon:  82.93
- name: Омск
  lat:  54.99
  lon:  73.37
- name: Самара
  lat:  53.20
  lon:  50.15
- name: Воронеж
  lat:  51.67
  lon:  39.18
- name: Ростов-на-Дону
  lat:  47.23
  lon:  39.72
- name: Нижний Новгород
  lat:  56.33
  lon:  44.00
